# -*- coding: utf-8 -*-
from abc import ABC, abstractmethod
class BrokerBase(ABC):
    @abstractmethod
    def update_market_price(self, ticker: str, price: float): ...
    @abstractmethod
    def place_order(self, order): ...
    @abstractmethod
    def cancel_order(self, order): ...
    @abstractmethod
    def get_positions(self): ...
    @abstractmethod
    def get_account_snapshot(self): ...
    @abstractmethod
    def restore_state(self, cash, positions, last_prices=None): ...
